"""001 core foundation

Revision ID: 0201cf10c56c
Revises: 
Create Date: 2026-08-28 11:58:57.199665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0201cf10c56c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idempotency_key',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('response_json', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idempotency_key_key'), 'idempotency_key', ['key'], unique=True)
    op.create_table('asset',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('household_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=300), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_household_id'), 'asset', ['household_id'], unique=False)
    op.create_table('audit_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('before_json', sa.Text(), nullable=True),
    sa.Column('after_json', sa.Text(), nullable=True),
    sa.Column('household_id', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_event_entity_id'), 'audit_event', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_event_household_id'), 'audit_event', ['household_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('household_id', sa.String(length=36), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('media_type', sa.String(length=100), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('source_kind', sa.String(length=50), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_evidence_household_id'), 'evidence', ['household_id'], unique=False)
    op.create_index(op.f('ix_evidence_sha256'), 'evidence', ['sha256'], unique=True)
    op.create_table('job',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('config_snapshot', sa.Text(), nullable=True),
    sa.Column('household_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_job_household_id'), 'job', ['household_id'], unique=False)
    op.create_table('review_task',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('subject_ref', sa.String(length=36), nullable=False),
    sa.Column('proposed_change', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('household_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_task_household_id'), 'review_task', ['household_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('household_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_household_id'), 'user', ['household_id'], unique=False)
    op.create_table('assertion',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('field_path', sa.String(length=200), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('review_state', sa.String(length=50), nullable=False),
    sa.Column('source_evidence_ids', sa.Text(), nullable=True),
    sa.Column('model_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assertion_asset_id'), 'assertion', ['asset_id'], unique=False)
    op.create_table('asset_evidence',
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', 'evidence_id')
    )
    op.create_table('job_step',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('input_refs', sa.Text(), nullable=True),
    sa.Column('output_refs', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_step_job_id'), 'job_step', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_step_job_id'), table_name='job_step')
    op.drop_table('job_step')
    op.drop_table('asset_evidence')
    op.drop_index(op.f('ix_assertion_asset_id'), table_name='assertion')
    op.drop_table('assertion')
    op.drop_index(op.f('ix_user_household_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_review_task_household_id'), table_name='review_task')
    op.drop_table('review_task')
    op.drop_index(op.f('ix_job_household_id'), table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_evidence_sha256'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_household_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_audit_event_household_id'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_entity_id'), table_name='audit_event')
    op.drop_table('audit_event')
    op.drop_index(op.f('ix_asset_household_id'), table_name='asset')
    op.drop_table('asset')
    op.drop_index(op.f('ix_idempotency_key_key'), table_name='idempotency_key')
    op.drop_table('idempotency_key')
    op.drop_table('household')
    # ### end Alembic commands ###
